# Generated by Django 4.2 on 2025-02-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
