# Generated by Django 4.2 on 2025-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_stock_price_stockhistory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='reorder_level',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
