# Generated by Django 4.2 on 2025-02-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_stockhistory_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
