# Generated by Django 5.0.6 on 2024-06-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='date',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
