# Generated by Django 4.2 on 2025-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_stock_total_amount_stockhistory_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='receive_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
